[package]
name = "braid-crypto"
version = "0.1.0"
authors = ["torrencem <matt@torrencefamily.net>"]

[dependencies]
indexmap = "1.0.1"
rand = "0.5.5"

serde = "1.0.80"
serde_derive = "1.0.80"
bincode = "1.0.1"